CREATE TABLE customer_risk_table (
    customer_id INTEGER,
    statement_month TEXT,
    limit_balance REAL,
    annual_income REAL,
    sex TEXT,
    education TEXT,
    marital_status TEXT,
    age INTEGER,
    age_group TEXT,
    credit_limit_band TEXT,
    utilization_ratio REAL,
    payment_ratio REAL,
    months_with_delay INTEGER,
    pay_status_1 INTEGER,
    pay_status_2 INTEGER,
    pay_status_3 INTEGER,
    pay_status_4 INTEGER,
    pay_status_5 INTEGER,
    pay_status_6 INTEGER,
    bill_amt_1 REAL,
    bill_amt_2 REAL,
    bill_amt_3 REAL,
    bill_amt_4 REAL,
    bill_amt_5 REAL,
    bill_amt_6 REAL,
    pay_amt_1 REAL,
    pay_amt_2 REAL,
    pay_amt_3 REAL,
    pay_amt_4 REAL,
    pay_amt_5 REAL,
    pay_amt_6 REAL,
    default_next_month INTEGER
);

